resolver: lts-21.0
packages:
- .
extra-deps:
- git: "https://github.com/d86leader/ron-hs.git"
  commit: "e01e6acd0970c3e236450e10aeff5f22e135ed42"
system-ghc: true
ghc-options:
  "$everything": "-split-sections"
