resolver: lts-22.43
packages:
- .
extra-deps:
- ron-hs-0.4.0@sha256:cb8e4f951549854d3c3531a2c3ba40e5fdbed2cc993852aaccf3f258ea64ee5d,3429
system-ghc: true
ghc-options:
  "$everything": "-split-sections"
